language: python

python:
  - "3.5"

env:
  - DJANGO=""   # no django
  - DJANGO="Django>=1.11,<1.12"

install:
  - pip install -e .
  - pip install -e '.[test]'
  - pip install -q $DJANGO
  - if [ $DJANGO != '' ]; then pip install django-autocomplete-light; fi
  - pip install codecov
  - cp ci/testsettings.py testsettings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> testsettings.py

script:
  - py.test --cov=viapy

after_success:
  - codecov
